export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Property } from "./Property";
export { default as Contact } from "./Contact";
export { default as Login } from "./Login";
export { default as Team } from "./Team";
export { default as SignUp } from "./SignUp";
export { default as PropertyDetails } from "./PropertyDetails";
export { default as PageNotFound } from "./PageNotFound";
